Stop init when Quantum plugin is activated and Java 1.7 is used

diff --git a/warp10/src/main/sh/warp10-standalone.init b/warp10/src/main/sh/warp10-standalone.init
--- a/warp10/src/main/sh/warp10-standalone.init
+++ b/warp10/src/main/sh/warp10-standalone.init
@@ -42,6 +42,8 @@ QUANTUM_PLUGIN_JAR=${WARP10_HOME}/bin/warp10-quantum-plugin-${QUANTUM_REVISION}.
 QUANTUM_PLUGIN_NAME=io.warp10.plugins.quantum.QuantumPlugin
 QUANTUM_STARTED=true
 
+IS_JAVA7=false
+
 WARP10_REVISION=@VERSION@
 WARP10_USER=warp10
 WARP10_CONFIG=${WARP10_HOME}/etc/conf-standalone.conf
@@ -116,6 +118,11 @@ start() {
     exit 1
   fi
 
+  CHECK_JAVA7="`su ${WARP10_USER} -c "${JAVA_HOME}/bin/java -version 2>&1 | head -n 1 | sed -e 's/.*\\"1.8.*//'"`"
+  if [ "$CHECK_JAVA7" != "" ]; then
+    IS_JAVA7=true
+  fi
+
   # warp10 user ?
   if ! id -u "${WARP10_USER}" >/dev/null 2>&1;
   then
@@ -179,10 +186,15 @@ start() {
   QUANTUM_PLUGIN="`su ${WARP10_USER} -c "${JAVA_HOME}/bin/java -Xms64m -Xmx64m -XX:+UseG1GC -cp ${WARP10_CP} io.warp10.WarpConfig ${WARP10_CONFIG} 'warp10.plugins'" | grep ${QUANTUM_PLUGIN_NAME}`"
 
   if [ "$QUANTUM_PLUGIN" != "" ]; then
-    QUANTUM_STARTED=true
-    QUANTUM_LISTENSTO_HOST="`su ${WARP10_USER} -c "${JAVA_HOME}/bin/java -Xms64m -Xmx64m -XX:+UseG1GC -cp ${WARP10_CP} io.warp10.WarpConfig ${WARP10_CONFIG} 'quantum.host'" | grep 'quantum.host' | sed -e 's/^.*=//'`"
-    QUANTUM_LISTENSTO_PORT="`su ${WARP10_USER} -c "${JAVA_HOME}/bin/java -Xms64m -Xmx64m -XX:+UseG1GC -cp ${WARP10_CP} io.warp10.WarpConfig ${WARP10_CONFIG} 'quantum.port'" | grep 'quantum.port' | sed -e 's/^.*=//'`"
-    QUANTUM_LISTENSTO="${QUANTUM_LISTENSTO_HOST}:${QUANTUM_LISTENSTO_PORT}"
+    if [ "$IS_JAVA7" = false ]; then
+      QUANTUM_STARTED=true
+      QUANTUM_LISTENSTO_HOST="`su ${WARP10_USER} -c "${JAVA_HOME}/bin/java -Xms64m -Xmx64m -XX:+UseG1GC -cp ${WARP10_CP} io.warp10.WarpConfig ${WARP10_CONFIG} 'quantum.host'" | grep 'quantum.host' | sed -e 's/^.*=//'`"
+      QUANTUM_LISTENSTO_PORT="`su ${WARP10_USER} -c "${JAVA_HOME}/bin/java -Xms64m -Xmx64m -XX:+UseG1GC -cp ${WARP10_CP} io.warp10.WarpConfig ${WARP10_CONFIG} 'quantum.port'" | grep 'quantum.port' | sed -e 's/^.*=//'`"
+      QUANTUM_LISTENSTO="${QUANTUM_LISTENSTO_HOST}:${QUANTUM_LISTENSTO_PORT}"
+    else
+      echo "Start failed! - Quantum is only Java 1.8+ compliant - To start Warp10 with Java7 comment out Quantum plugin in the Warp config file"
+      exit 1
+    fi
   else
     QUANTUM_STARTED=false
     # Delete Quantum from CP
