standalone init + snapshot revamped to be run as warp10 user

diff --git a/warp10/src/main/sh/warp10-standalone.init b/warp10/src/main/sh/warp10-standalone.init
--- a/warp10/src/main/sh/warp10-standalone.init
+++ b/warp10/src/main/sh/warp10-standalone.init
@@ -7,16 +7,6 @@
 # description: Manage Standalone instance of Warp 10
 #
 
-#
-# Make sure the caller is root
-#
-
-if [ "`whoami`" != "root" ]
-then
-  echo "You must be root to run this script."
-  exit 1
-fi
-
 OS=$(uname -s)
 
 #JAVA_HOME=/opt/java8
@@ -93,8 +83,45 @@ JAVA_HEAP_DUMP=${WARP10_HOME}/logs/java.heapdump
 JAVA_OPTS="-Djava.awt.headless=true -Dlog4j.configuration=file:${LOG4J_CONF} -Dsensision.server.port=0 -Dsensision.events.dir=${SENSISION_EVENTS_DIR} -Xms${WARP10_HEAP} -Xmx${WARP10_HEAP_MAX} -XX:+UseG1GC"
 export MALLOC_ARENA_MAX=1
 
-initConfig() {
-  echo "Init config.."
+bootstrap() {
+  echo "Bootstrap.."
+
+  #
+  # Make sure the caller is root
+  #
+
+  if [ "`whoami`" != "root" ]
+  then
+    echo "You must be root to run 'bootstrap' command."
+    exit 1
+  fi
+
+  # warp10 user ?
+  if ! id -u "${WARP10_USER}" >/dev/null 2>&1;
+  then
+    echo "User '${WARP10_USER}'' does not exist - Creating it.."
+    # Create user warp10
+    if [ "`which useradd`" = "" ]
+    then
+      if [ "`which adduser`" != "" ]
+      then
+        adduser -D -s -H -h ${WARP10_HOME} -s /bin/bash ${WARP10_USER}
+      else
+        echo "Hmmm that's embarassing but I do not know how to create the ${WARP10_USER} user with home directory ${WARP10_HOME}, could you do it for me and run the script again?"
+        exit 1
+      fi
+    else
+      useradd -d ${WARP10_HOME} -M -r ${WARP10_USER} -s /bin/bash
+    fi
+  fi
+
+  #
+  # If config file already exists then.. exit 
+  #
+  if [ -e ${WARP10_CONFIG} ]; then
+    echo "Config file already exists - Abort bootstrap..."
+    exit 2
+  fi
 
   # Fix ownership
   echo "Fix ownership.."
@@ -308,7 +335,18 @@ initConfig() {
 }
 
 start() {
-  CHECK_JAVA7="`su ${WARP10_USER} -c "${JAVA_HOME}/bin/java -version 2>&1 | head -n 1 | grep '.*\\"1.7.*'"`"
+
+  #
+  # Make sure the caller is warp10
+  #
+
+  if [ "`whoami`" != "${WARP10_USER}" ]
+  then
+    echo "You must be ${WARP10_USER} to run this script."
+    exit 1
+  fi
+
+  CHECK_JAVA7="`${JAVA_HOME}/bin/java -version 2>&1 | head -n 1 | grep '.*\\"1.7.*'`"
   if [ "$CHECK_JAVA7" != "" ]; then
     IS_JAVA7=true
   fi
@@ -316,27 +354,15 @@ start() {
   # warp10 user ?
   if ! id -u "${WARP10_USER}" >/dev/null 2>&1;
   then
-    echo "User '${WARP10_USER}'' does not exist - Creating it.."
-    # Create user warp10
-    if [ "`which useradd`" = "" ]
-    then
-      if [ "`which adduser`" != "" ]
-      then
-        adduser -D -s -H -h ${WARP10_HOME} -s /bin/bash ${WARP10_USER}
-      else
-        echo "Hmmm that's embarassing but I do not know how to create the ${WARP10_USER} user with home directory ${WARP10_HOME}, could you do it for me and run the script again?"
-        exit 1
-      fi
-    else
-      useradd -d ${WARP10_HOME} -M -r ${WARP10_USER} -s /bin/bash
-    fi
+    echo "User '${WARP10_USER}'' does not exist - Use 'bootstrap' command (it must be run as root)"
+    exit 1
   fi
 
   if [ -f ${JAVA_HEAP_DUMP} ]; then
     mv ${JAVA_HEAP_DUMP} ${JAVA_HEAP_DUMP}-`date +%s`
   fi
 
-  if [ "`su ${WARP10_USER} -c "${JAVA_HOME}/bin/jps -lm|grep ${WARP10_CLASS}|cut -f 1 -d' '"`" != "" ]; then
+  if [ "`${JAVA_HOME}/bin/jps -lm|grep ${WARP10_CLASS}|cut -f 1 -d' '`" != "" ]; then
     echo "Start failed! - A Warp 10 instance is currently running"
     exit 1
   fi
@@ -345,18 +371,18 @@ start() {
   # Config file exists ?
   #
   if [ ! -e ${WARP10_CONFIG} ]; then
-    echo "Config file does not exist - Creating it from template..."
-    initConfig
+    echo "Config file does not exist - Use 'bootstrap' command (it must be run as root)"
+    exit 1
   fi
 
-  LEVELDB_HOME="`su ${WARP10_USER} -c "${JAVA_HOME}/bin/java -Xms64m -Xmx64m -XX:+UseG1GC -cp ${WARP10_CP} io.warp10.WarpConfig ${WARP10_CONFIG} 'leveldb.home'" | grep 'leveldb.home' | sed -e 's/^.*=//'`"
+  LEVELDB_HOME="`${JAVA_HOME}/bin/java -Xms64m -Xmx64m -XX:+UseG1GC -cp ${WARP10_CP} io.warp10.WarpConfig ${WARP10_CONFIG} 'leveldb.home' | grep 'leveldb.home' | sed -e 's/^.*=//'`"
 
   #
   # Leveldb exists ?
   #
   if [ ! -e ${LEVELDB_HOME} ]; then
     echo "${LEVELDB_HOME} does not exist - Creating it..."
-    su ${WARP10_USER} -c "mkdir -p ${LEVELDB_HOME} 2>&1"
+    mkdir -p ${LEVELDB_HOME} 2>&1
     if [ $? != 0 ]; then
       echo "${LEVELDB_HOME} creation failed"
       exit 1
@@ -366,26 +392,26 @@ start() {
   if [ "$(find -L ${LEVELDB_HOME} -maxdepth 1 -type f | wc -l)" -eq 0 ]; then
     echo "Init leveldb"
     # Create leveldb database
-    su ${WARP10_USER} -c "echo \"Init leveldb database...\" >> ${WARP10_HOME}/logs/warp10.log"
-    su ${WARP10_USER} -c "${JAVA_HOME}/bin/java ${JAVA_OPTS} -cp ${WARP10_CP} ${WARP10_INIT} ${LEVELDB_HOME} >> ${WARP10_HOME}/logs/warp10.log 2>&1"
+    echo \"Init leveldb database...\" >> ${WARP10_HOME}/logs/warp10.log
+    ${JAVA_HOME}/bin/java ${JAVA_OPTS} -cp ${WARP10_CP} ${WARP10_INIT} ${LEVELDB_HOME} >> ${WARP10_HOME}/logs/warp10.log 2>&1
   fi
 
-  WARP10_LISTENSTO_HOST="`su ${WARP10_USER} -c "${JAVA_HOME}/bin/java -Xms64m -Xmx64m -XX:+UseG1GC -cp ${WARP10_CP} io.warp10.WarpConfig ${WARP10_CONFIG} 'standalone.host'" | grep 'standalone.host' | sed -e 's/^.*=//'`"
-  WARP10_LISTENSTO_PORT="`su ${WARP10_USER} -c "${JAVA_HOME}/bin/java -Xms64m -Xmx64m -XX:+UseG1GC -cp ${WARP10_CP} io.warp10.WarpConfig ${WARP10_CONFIG} 'standalone.port'" | grep 'standalone.port' | sed -e 's/^.*=//'`"
+  WARP10_LISTENSTO_HOST="`${JAVA_HOME}/bin/java -Xms64m -Xmx64m -XX:+UseG1GC -cp ${WARP10_CP} io.warp10.WarpConfig ${WARP10_CONFIG} 'standalone.host' | grep 'standalone.host' | sed -e 's/^.*=//'`"
+  WARP10_LISTENSTO_PORT="`${JAVA_HOME}/bin/java -Xms64m -Xmx64m -XX:+UseG1GC -cp ${WARP10_CP} io.warp10.WarpConfig ${WARP10_CONFIG} 'standalone.port' | grep 'standalone.port' | sed -e 's/^.*=//'`"
   WARP10_LISTENSTO="${WARP10_LISTENSTO_HOST}:${WARP10_LISTENSTO_PORT}"
 
   #
   # Check if Warp10 Quantum plugin is defined
   #
-  QUANTUM_PLUGIN="`su ${WARP10_USER} -c "${JAVA_HOME}/bin/java -Xms64m -Xmx64m -XX:+UseG1GC -cp ${WARP10_CP} io.warp10.WarpConfig ${WARP10_CONFIG} 'warp10.plugins'" | grep ${QUANTUM_PLUGIN_NAME}`"
+  QUANTUM_PLUGIN="`${JAVA_HOME}/bin/java -Xms64m -Xmx64m -XX:+UseG1GC -cp ${WARP10_CP} io.warp10.WarpConfig ${WARP10_CONFIG} 'warp10.plugins' | grep ${QUANTUM_PLUGIN_NAME}`"
 
   if [ "$QUANTUM_PLUGIN" != "" ]; then
     if [ "$IS_JAVA7" = false ]; then
       IS_QUANTUM_STARTED=true
       # Add Quantum to WARP10_CP
       WARP10_CP=${QUANTUM_PLUGIN_JAR}:${WARP10_CP}
-      QUANTUM_LISTENSTO_HOST="`su ${WARP10_USER} -c "${JAVA_HOME}/bin/java -Xms64m -Xmx64m -XX:+UseG1GC -cp ${WARP10_CP} io.warp10.WarpConfig ${WARP10_CONFIG} 'quantum.host'" | grep 'quantum.host' | sed -e 's/^.*=//'`"
-      QUANTUM_LISTENSTO_PORT="`su ${WARP10_USER} -c "${JAVA_HOME}/bin/java -Xms64m -Xmx64m -XX:+UseG1GC -cp ${WARP10_CP} io.warp10.WarpConfig ${WARP10_CONFIG} 'quantum.port'" | grep 'quantum.port' | sed -e 's/^.*=//'`"
+      QUANTUM_LISTENSTO_HOST="`${JAVA_HOME}/bin/java -Xms64m -Xmx64m -XX:+UseG1GC -cp ${WARP10_CP} io.warp10.WarpConfig ${WARP10_CONFIG} 'quantum.host' | grep 'quantum.host' | sed -e 's/^.*=//'`"
+      QUANTUM_LISTENSTO_PORT="`${JAVA_HOME}/bin/java -Xms64m -Xmx64m -XX:+UseG1GC -cp ${WARP10_CP} io.warp10.WarpConfig ${WARP10_CONFIG} 'quantum.port' | grep 'quantum.port' | sed -e 's/^.*=//'`"
       QUANTUM_LISTENSTO="${QUANTUM_LISTENSTO_HOST}:${QUANTUM_LISTENSTO_PORT}"
     else
       echo "Start failed! - Quantum is only Java 1.8+ compliant - To start Warp10 with Java7 comment out Quantum plugin in the Warp config file"
@@ -399,9 +425,9 @@ start() {
   #
   # Start Warp10 instance..
   #
-  su ${WARP10_USER} -c "${JAVA_HOME}/bin/java ${JAVA_OPTS} -cp ${WARP10_CP} ${WARP10_CLASS} ${WARP10_CONFIG} >> ${WARP10_HOME}/logs/warp10.log 2>&1 &"
+  ${JAVA_HOME}/bin/java ${JAVA_OPTS} -cp ${WARP10_CP} ${WARP10_CLASS} ${WARP10_CONFIG} >> ${WARP10_HOME}/logs/warp10.log 2>&1 &
 
-  if [ "`su ${WARP10_USER} -c "${JAVA_HOME}/bin/jps -lm|grep ${WARP10_CLASS}|cut -f 1 -d' '"`" = "" ]; then
+  if [ "`${JAVA_HOME}/bin/jps -lm|grep ${WARP10_CLASS}|cut -f 1 -d' '`" = "" ]; then
     echo "Start failed! - See warp10.log for more details"
     exit 1
   fi
@@ -451,17 +477,39 @@ start() {
 }
 
 stop() {
-  echo "Stop Warp10..."
-  if [ "`su ${WARP10_USER} -c "${JAVA_HOME}/bin/jps -lm|grep ${WARP10_CLASS}|cut -f 1 -d' '"`" != "" ]
+
+  #
+  # Make sure the caller is warp10
+  #
+
+  if [ "`whoami`" != "${WARP10_USER}" ]
   then
-    kill `su ${WARP10_USER} -c "${JAVA_HOME}/bin/jps -lm|grep ${WARP10_CLASS}|cut -f 1 -d' '"`
+    echo "You must be ${WARP10_USER} to run this script."
+    exit 1
+  fi
+
+  echo "Stop Warp10..."
+  if [ "`${JAVA_HOME}/bin/jps -lm|grep ${WARP10_CLASS}|cut -f 1 -d' '`" != "" ]
+  then
+    kill `${JAVA_HOME}/bin/jps -lm|grep ${WARP10_CLASS}|cut -f 1 -d' '`
   else
     echo "No instance of Warp 10 is currently running"
   fi
 }
 
 status() {
-  su ${WARP10_USER} -c "${JAVA_HOME}/bin/jps -lm|grep ${WARP10_CLASS}"
+  
+  #
+  # Make sure the caller is warp10
+  #
+
+  if [ "`whoami`" != "${WARP10_USER}" ]
+  then
+    echo "You must be ${WARP10_USER} to run this script."
+    exit 1
+  fi
+
+  ${JAVA_HOME}/bin/jps -lm|grep ${WARP10_CLASS}
 }
 
 snapshot() {
@@ -471,15 +519,29 @@ snapshot() {
 }
 
 worf() {
+  
+  #
+  # Make sure the caller is warp10
+  #
+
+  if [ "`whoami`" != "${WARP10_USER}" ]
+  then
+    echo "You must be ${WARP10_USER} to run this script."
+    exit 1
+  fi
+
   if [ "$#" -ne 3 ]; then
     echo "Usage: $0 $1 appName ttl(ms)"
     exit 1
   fi
-  su ${WARP10_USER} -c "${JAVA_HOME}/bin/java -cp ${WARP10_JAR} io.warp10.worf.Worf ${WARP10_CONFIG} -puidg -t -a $2 -ttl $3"
+  ${JAVA_HOME}/bin/java -cp ${WARP10_JAR} io.warp10.worf.Worf ${WARP10_CONFIG} -puidg -t -a $2 -ttl $3
 }
 
 # See how we were called.
 case "$1" in
+  bootstrap)
+  bootstrap
+  ;;
   start)
   start
   ;;
@@ -501,7 +563,7 @@ case "$1" in
   snapshot "$2"
   ;;
   *)
-  echo $"Usage: $0 {start|stop|status|worf appName ttl(ms)|snapshot 'snapshot_name'}"
+  echo $"Usage: $0 {bootstrap|start|stop|status|worf appName ttl(ms)|snapshot 'snapshot_name'}"
   exit 2
 esac
 
